version: "3.9"

services: 
  nats:
    build: 
      context: nats/
    ports:
      - "4222:4222"
      - "8222:8222"
      - "8443:443"

    volumes: 
      - "~/fwcerts:/certs"
      - "./nats:/conf"
